services:
  postgres:
    image: postgres:17
    container_name: budgetfriend.api-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: budgetfriend_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./src
      dockerfile: dockerfile

    container_name: budgetfriend.api

    depends_on:
      - postgres

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Jwt__SecretKey: ${JWT_SECRET}

      ConnectionStrings__Database: Host=postgres;Port=5432;Database=budgetfriend_db;Username=postgres;Password=postgres
      ConnectionStrings__Redis: redis:6379

      OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire-dashboard:18890
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf

    ports:
      - "8080:8080"

  redis:
    image: redis:8-alpine
    container_name: budgetfriend.redis
    restart: unless-stopped

    ports:
      - "6379:6379"

  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    container_name: budgetfriend.aspire-dashboard
    restart: unless-stopped

    environment:
      ASPNETCORE_URLS: http://0.0.0.0:18888
      ASPIRE_DASHBOARD_OTLP_ENDPOINT_URL: http://0.0.0.0:18889
      ASPIRE_DASHBOARD_OTLP_HTTP_ENDPOINT_URL: http://0.0.0.0:18890
      DASHBOARD__OTLP__AUTHMODE: Unsecured
      DASHBOARD__FRONTEND__AUTHMODE: Unsecured

    ports:
      - "18888:18888"
      - "4317:18889"
      - "4318:18890"

volumes:
  postgres_data:
